### ISSUE TITLE
grunt serve not always works

### ISSUE THREAD

**Issue by dKab** [seyDoggy/yo-angular-php-crud#1]
I don't know how to explain it but sometimes when I run `grunt serve` it doesn't work. Here is output:

$ grunt --gruntfile /home/dmitriy/study/js/fm-app/Gruntfile.js serve
Running "serve" task

Running "clean:server" (clean) task

Running "wiredep:app" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task

```
Running "compass:server" (compass) task

Done, without errors.


Execution Time (2015-02-22 07:58:38 UTC)
compass:server  3.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 3.9s
```

Running "autoprefixer:dist" (autoprefixer) task

Running "php:livereload" (php) task
[Sun Feb 22 12:58:42 2015] 127.0.0.1:58869 [200]: /

Running "watch" task
Waiting...
[Sun Feb 22 12:58:42 2015] 127.0.0.1:58870 [200]: /

Done, without errors.

Execution Time (2015-02-22 07:58:34 UTC)
wiredep:app         1.4s  ▇▇▇▇▇▇▇▇ 17%
concurrent:server   6.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 80%
php:livereload     157ms  ▇ 2%
Total 8.1s

Process finished with exit code 0

It can happen several times in a row, but then it starts normally as if nothing were wrong, although I don't change anything in configuration... 

Here is an output of successfull try:

$ grunt --gruntfile /home/dmitriy/study/js/fm-app/Gruntfile.js serve
Running "serve" task

Running "clean:server" (clean) task

Running "wiredep:app" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task

```
Running "compass:server" (compass) task

Done, without errors.


Execution Time (2015-02-22 08:04:57 UTC)
compass:server  639ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 644ms
```

Running "autoprefixer:dist" (autoprefixer) task

Running "php:livereload" (php) task
[Sun Feb 22 13:04:58 2015] 127.0.0.1:58917 [200]: /

Running "watch" task
Waiting...
[Sun Feb 22 13:04:59 2015] 127.0.0.1:58918 [200]: /
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58919 [200]: /bower_components/angular-sanitize/angular-sanitize.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58920 [200]: /styles/main.css
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58921 [200]: /bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58922 [200]: /bower_components/jquery/dist/jquery.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58923 [200]: /bower_components/angular/angular.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58924 [200]: /bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58926 [200]: /bower_components/angular-animate/angular-animate.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58927 [200]: /bower_components/angular-cookies/angular-cookies.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58928 [200]: /bower_components/angular-resource/angular-resource.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58929 [200]: /bower_components/angular-route/angular-route.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58930 [200]: /bower_components/angular-touch/angular-touch.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58931 [200]: /scripts/app.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58932 [200]: /scripts/controllers/main.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58933 [200]: /scripts/controllers/about.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58934 [200]: /scripts/controllers/categories.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58935 [200]: /scripts/controllers/signup.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58936 [200]: /scripts/directives/value-match.js
[Sun Feb 22 13:05:00 2015] 127.0.0.1:58937 [200]: /views/main.html
[Sun Feb 22 13:05:01 2015] 127.0.0.1:58938 [200]: /favicon.ico
[Sun Feb 22 13:05:01 2015] 127.0.0.1:58939 [200]: /images/yeoman.png
[Sun Feb 22 13:05:01 2015] 127.0.0.1:58940 [200]: /favicon.ico
[Sun Feb 22 13:05:01 2015] 127.0.0.1:58941 [200]: /favicon.ico

Execution Time (2015-02-22 08:04:54 UTC)
PHP 5.5.9-1ubuntu4.6 Development Server started at Sun Feb 22 13:04:58 2015
Listening on http://localhost:9000
Document root is /home/dmitriy/study/js/fm-app/app
Press Ctrl-C to quit.
watch          9m 4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 9m 7.6s

Process finished with exit code 0

**Comment by seyDoggy** [comment]
What happens when you `cd` into the root of fm-app and just use `grunt
serve`?

Adam Merrifield
+1 (519) 574-9788

**Comment by dKab** [comment]
fm-app (master)$ grunt serve
Running "serve" task

Running "clean:server" (clean) task

Running "wiredep:app" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task

```
Running "compass:server" (compass) task

Done, without errors.


Execution Time (2015-02-22 13:35:04 UTC)
compass:server  666ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 672ms
```

Running "autoprefixer:dist" (autoprefixer) task

Running "php:livereload" (php) task
PHP 5.5.9-1ubuntu4.6 Development Server started at Sun Feb 22 18:35:06 2015
Listening on http://localhost:9000
Document root is /home/dmitriy/study/js/fm-app/app
Press Ctrl-C to quit.
[Sun Feb 22 18:35:06 2015] 127.0.0.1:33585 [200]: /

Running "watch" task
Waiting...
[Sun Feb 22 18:35:06 2015] 127.0.0.1:33586 [200]: /

Done, without errors.

Execution Time (2015-02-22 13:35:01 UTC)
wiredep:app        192ms  ▇▇▇▇▇▇▇▇▇ 4%
concurrent:server   3.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 75%
php:livereload     769ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 18%
watch               60ms  ▇▇▇ 1%
Total 4.3s

I believe that's same thing - I tried it already. Browser opens http://localhost:9000  and all I can see is `Unable to connect` message.

**Comment by dKab** [comment]
but then again, when I try it after a few minutes later - it works fine. That's very suspicious and strange... Anyway, I just thought you may have  encountered  this too and would know how to solve it, but it seems it's just me.

**Comment by seyDoggy** [comment]
Have you tried locking in the dependency version to the exact versions listed in the [package.json](https://github.com/seyDoggy/yo-angular-php-crud/blob/master/package.json)? i.e. change `"grunt-php": "^1.1.0",` to `"grunt-php": "1.1.0",` and so on... Maybe you're hitting a version of something that throws errors.
